[package]
name = "silkenweb-htmx-axum"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true, features = ["headers"] }
serde = { workspace = true }
serde_urlencoded = { workspace = true }
silkenweb = { workspace = true }
