[package]
name = "silkenweb-htmx-axum"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.66"
axum = "0.6.10"
serde = "1.0.154"
serde_urlencoded = "0.7.1"
silkenweb = { path = "../silkenweb" }
