[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
xtask-base = { workspace = true }
xshell = { workspace = true }
duct = { workspace = true }
scopeguard = { workspace = true }
itertools = { workspace = true }
