[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
xtask-base = { git = "https://github.com/simon-bourne/rust-xtask-base" }
xshell = "0.1.17"
duct = "0.13.5"
scopeguard = "1.1.0"
itertools = "0.10.3"
