[package]
name = "silkenweb-tauri"
version = "0.3.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
description = "Silkenweb Tauri integration"
homepage = "https://github.com/silkenweb/silkenweb"
repository = "https://github.com/silkenweb/silkenweb"
license = "MIT OR Apache-2.0"

categories = ["gui"]
keywords = ["silkenweb", "tauri"]

[dependencies]
silkenweb-tauri-proc-macro = { version = "0.3.0", path = "../tauri-proc-macro" }
js-sys = "0.3.60"
wasm-bindgen = { version = "=0.2.83", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.33"
static_assertions = "1.1.0"
