[package]
name = "silkenweb-tauri"
version = "0.4.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
description = "Silkenweb Tauri integration"
homepage = "https://github.com/silkenweb/silkenweb"
repository = "https://github.com/silkenweb/silkenweb"
license = "MIT OR Apache-2.0"

categories = ["gui"]
keywords = ["silkenweb", "tauri"]

[dependencies]
silkenweb-tauri-proc-macro = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
static_assertions = { workspace = true }
serde-wasm-bindgen = { workspace = true }
