[package]
name = "silkenweb-example-hackernews-clone"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
futures-signals = "0.3.24"
reqwasm = "0.4.1"
silkenweb = { path = "../../packages/silkenweb" }
