[package]
name = "silkenweb-example-inline-svg"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = { workspace = true }
silkenweb-inline-svg  = { workspace = true }
