[package]
name = "silkenweb-example-request"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
futures-signals = "0.3.24"
reqwest = "0.11.9"
silkenweb = { path = "../../packages/silkenweb" }
