[workspace]

members = ["packages/*", "examples/*"]
default-members = ["packages/*"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"

[patch.crates-io]
silkenweb-base = { path = "packages/base" }
silkenweb-signals-ext = { path = "packages/signals-ext" }
silkenweb-macros = { path = "packages/macros" }
silkenweb = { path = "packages/silkenweb" }
