[workspace]

members = [
    "examples/counter",
    "examples/memoized-counters",
    "examples/incremental-counters",
    "examples/todomvc",
    "crates/silkenweb",
    "crates/html",
    "crates/dom",
    "crates/reactive",
]

[profile.release]
codegen-units = 1
lto = true
