[workspace]

members = [
    "tutorial/counter",
    "tutorial/nested-counters",
    "tutorial/memoized-counters",
    "tutorial/reactive-list-counters",
    "tutorial/common",
    "examples/todomvc",
    "crates/silkenweb",
    "crates/html",
    "crates/dom",
    "crates/reactive",
]

[profile.release]
codegen-units = 1
lto = true
