[workspace]

members = ["packages/*", "examples/*"]
default-members = ["packages/*"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"

[patch.crates-io]
silkenweb-elements = { path = "packages/elements" }
silkenweb-dom = { path = "packages/dom" }
silkenweb-signals-ext = { path = "packages/signals-ext" }
silkenweb = { path = "packages/silkenweb" }
