[workspace]

members = [
    "examples/ui5-showcase",
    # "examples/todomvc",
    "examples/counter",
    "examples/counter-list",
    "examples/router",
    "examples/animation",
    "examples/hello-world",
    "crates/silkenweb",
    "crates/ui5",
    "crates/html",
    "crates/dom",
    "crates/reactive",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"

[patch.crates-io]
silkenweb-html = { path = "crates/html" }
silkenweb-dom = { path = "crates/dom" }
silkenweb-reactive = { path = "crates/reactive" }
silkenweb = { path = "crates/silkenweb" }
