[workspace]

members = [
    "tutorial/counter",
    "tutorial/counter-signal",
    "tutorial/counter-list",
    "tutorial/memoized-counter-list",
    "tutorial/reactive-counter-list",
    "tutorial/common",
    "examples/todomvc",
    "examples/counter",
    "examples/router",
    "examples/animation",
    "examples/hello-world",
    "crates/silkenweb",
    "crates/html",
    "crates/dom",
    "crates/reactive",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"

[patch.crates-io]
silkenweb-html = { path = "crates/html" }
silkenweb-dom = { path = "crates/dom" }
silkenweb-reactive = { path = "crates/reactive" }
