[workspace]

members = ["examples/*", "crates/*"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"

[patch.crates-io]
silkenweb-elements = { path = "crates/elements" }
silkenweb-dom = { path = "crates/dom" }
silkenweb-signals-ext = { path = "crates/signals-ext" }
silkenweb = { path = "crates/silkenweb" }
