[workspace]

members = [
    "examples/ui5-showcase",
    "examples/todomvc",
    "examples/counter",
    "examples/counter-list",
    "examples/router",
    "examples/animation",
    "examples/hello-world",
    "examples/js-framework-benchmark",
    "crates/silkenweb",
    "crates/ui5",
    "crates/elements",
    "crates/dom",
    "crates/signals-ext",
    "crates/xtask",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"

[patch.crates-io]
silkenweb-elements = { path = "crates/elements" }
silkenweb-dom = { path = "crates/dom" }
silkenweb-signals-ext = { path = "crates/signals-ext" }
silkenweb = { path = "crates/silkenweb" }
