[workspace]

members = [
    "crates/examples/counter",
    "crates/examples/nested-counters",
    "crates/examples/incremental-counters",
    "crates/examples/todomvc",
    "crates/html",
    "crates/core",
    "crates/silkenweb",
]

[profile.release]
codegen-units = 1
lto = true
