[package]
name = "silkenweb"
version = "0.4.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
description = "A library for building web apps"
readme = "../../README.md"
homepage = "https://github.com/silkenweb/silkenweb"
repository = "https://github.com/silkenweb/silkenweb"
license = "MIT OR Apache-2.0"

categories = ["gui", "web-programming"]
keywords = ["reactive", "web", "html", "browser", "dom"]

[features]
weak-refs = []
declarative-shadow-dom = []
sass = ["silkenweb-macros/sass"]

[dependencies]
discard = { workspace = true }
js-sys = { workspace = true }
futures = { workspace = true }
caseless = { workspace = true }
html-escape = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
silkenweb-base = { workspace = true }
silkenweb-signals-ext = { workspace = true }
silkenweb-macros = { workspace = true }
paste = { workspace = true }
wasm-bindgen = { workspace = true }
futures-signals = { workspace = true }
console_error_panic_hook = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
    "AnimationEvent",
    "Attr",
    "CompositionEvent",
    "css",
    "CssStyleDeclaration",
    "CustomEvent",
    "Document",
    "DomTokenList",
    "DragEvent",
    "Element",
    "FocusEvent",
    "History",
    "InputEvent",
    "KeyboardEvent",
    "Location",
    "MouseEvent",
    "NamedNodeMap",
    "Node",
    "Performance",
    "PointerEvent",
    "SecurityPolicyViolationEvent",
    "ShadowRoot",
    "ShadowRootInit",
    "ShadowRootMode",
    "Storage",
    "Text",
    "TouchEvent",
    "TransitionEvent",
    "WebGlContextEvent",
    "Url",
    "WheelEvent",
    "Window",

    "HtmlAnchorElement",
    "HtmlAreaElement",
    "HtmlAudioElement",
    "HtmlBaseElement",
    "HtmlBrElement",
    "HtmlButtonElement",
    "HtmlCanvasElement",
    "HtmlDataElement",
    "HtmlDataListElement",
    "HtmlDetailsElement",
    "HtmlDialogElement",
    "HtmlDivElement",
    "HtmlDListElement",
    "HtmlElement",
    "HtmlEmbedElement",
    "HtmlFieldSetElement",
    "HtmlFormElement",
    "HtmlHeadElement",
    "HtmlHeadingElement",
    "HtmlHrElement",
    "HtmlIFrameElement",
    "HtmlImageElement",
    "HtmlInputElement",
    "HtmlLabelElement",
    "HtmlLegendElement",
    "HtmlLiElement",
    "HtmlLinkElement",
    "HtmlMapElement",
    "HtmlMenuElement",
    "HtmlMetaElement",
    "HtmlMeterElement",
    "HtmlModElement",
    "HtmlObjectElement",
    "HtmlOListElement",
    "HtmlOptGroupElement",
    "HtmlOptionElement",
    "HtmlOutputElement",
    "HtmlParagraphElement",
    "HtmlParamElement",
    "HtmlPictureElement",
    "HtmlPreElement",
    "HtmlProgressElement",
    "HtmlQuoteElement",
    "HtmlScriptElement",
    "HtmlSelectElement",
    "HtmlSlotElement",
    "HtmlSourceElement",
    "HtmlSpanElement",
    "HtmlStyleElement",
    "HtmlTableCaptionElement",
    "HtmlTableCellElement",
    "HtmlTableColElement",
    "HtmlTableElement",
    "HtmlTableRowElement",
    "HtmlTableSectionElement",
    "HtmlTextAreaElement",
    "HtmlTimeElement",
    "HtmlTitleElement",
    "HtmlTrackElement",
    "HtmlUListElement",
    "HtmlVideoElement",

    "SvgaElement",
    "SvgCircleElement",
    "SvgClipPathElement",
    "SvgDefsElement",
    "SvgDescElement",
    "SvgEllipseElement",
    "SvgfeBlendElement",
    "SvgfeColorMatrixElement",
    "SvgfeComponentTransferElement",
    "SvgfeCompositeElement",
    "SvgfeConvolveMatrixElement",
    "SvgfeDiffuseLightingElement",
    "SvgfeDisplacementMapElement",
    "SvgfeDistantLightElement",
    "SvgfeFloodElement",
    "SvgfeFuncAElement",
    "SvgfeFuncBElement",
    "SvgfeFuncGElement",
    "SvgfeFuncRElement",
    "SvgfeGaussianBlurElement",
    "SvgfeImageElement",
    "SvgfeMergeElement",
    "SvgfeMergeNodeElement",
    "SvgfeMorphologyElement",
    "SvgfeOffsetElement",
    "SvgfePointLightElement",
    "SvgfeSpecularLightingElement",
    "SvgfeSpotLightElement",
    "SvgfeTileElement",
    "SvgfeTurbulenceElement",
    "SvgFilterElement",
    "SvggElement",
    "SvgLineElement",
    "SvgLinearGradientElement",
    "SvgMarkerElement",
    "SvgMaskElement",
    "SvgMetadataElement",
    "SvgmPathElement",
    "SvgPatternElement",
    "SvgPolygonElement",
    "SvgPolylineElement",
    "SvgRadialGradientElement",
    "SvgScriptElement",
    "SvgSetElement",
    "SvgStopElement",
    "SvgStyleElement",
    "SvgSwitchElement",
    "SvgSymbolElement",
    "SvgTextElement",
    "SvgTextPathElement",
    "SvgTitleElement",
    "SvgtSpanElement",
    "SvgViewElement",
    "SvgsvgElement",
    "SvgPathElement",
    "SvgRectElement",
    "SvgUseElement",
]

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
wasm-bindgen-futures = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
itertools = { workspace = true }
criterion = { workspace = true, default-features = false }
trybuild = { workspace = true }

[[bench]]
name = "ssr"
harness = false
