[package]
name = "silkenweb-example-inline-svgs"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = { workspace = true }
silkenweb-inline-svgs  = { workspace = true }
