[package]
name = "surfinia-html"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2018"

[dependencies]
surfinia-core = { path = "../core" }
paste = "1.0"
web-sys = "0.3"
wasm-bindgen = "0.2"
