[package]
name = "silkenweb-tutorial-counter-list"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = { path = "../../crates/silkenweb" }
silkenweb-tutorial-common = { path = "../common" }
