[package]
name = "silkenweb-example-async-http-request"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
futures-signals = { workspace = true }
reqwasm = { workspace = true }
silkenweb = { workspace = true }
