[package]
name = "silkenweb-signals-ext"
version = { workspace = true }
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
description = "Extras for futures-signals"
homepage = "https://github.com/silkenweb/silkenweb"
repository = "https://github.com/silkenweb/silkenweb"
license = "MIT OR Apache-2.0"

categories = ["gui"]
keywords = ["reactive"]

[dependencies]
futures-signals = { workspace = true }
pin-project = { workspace = true }
paste = { workspace = true }
