[package]
name = "silkenweb-examples-nested-counters"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2018"

[dependencies]
silkenweb-core = { path = "../../core" }
silkenweb-html = { path = "../../html" }
console_error_panic_hook = "*"
web-log = "*"
