[workspace]
resolver = "2"
members = ["packages/*"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"

[workspace.dependencies]
silkenweb = { path = "../../packages/silkenweb" }
ssr-full-app = { path = "packages/app" }
wasm-bindgen = "0.2.84"
web-log = "1.0.1"
