[package]
name = "silkenweb-example-animation"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = { path = "../../packages/silkenweb" }
futures-signals = "0.3.31"
num-traits = "0.2.15"
wasm-bindgen = "=0.2.83"