[package]
name = "silkenweb-ui5"
version = "0.3.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
description = "UI5 bindings for Silkenweb"
readme = "README.md"
homepage = "https://github.com/silkenweb/silkenweb"
repository = "https://github.com/silkenweb/silkenweb"
license = "MIT OR Apache-2.0"

categories = ["gui", "web-programming"]
keywords = ["reactive", "web", "html", "browser", "dom"]

[dependencies]
silkenweb = { path = "../silkenweb", version = "0.3.0" }
web-sys = "0.3.60"
wasm-bindgen = "=0.2.83"
js-sys = "0.3.60"
parse-display= "0.5.5"
futures-signals = "0.3.24"
chrono = "0.4.19"
paste = "1.0.6"
