[package]
name = "silkenweb-ui5"
version = "0.2.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
description = "UI5 bindings for Silkenweb"
readme = "README.md"
homepage = "https://github.com/silkenweb/silkenweb"
repository = "https://github.com/silkenweb/silkenweb"
license = "MIT OR Apache-2.0"

categories = ["gui", "web-programming"]
keywords = ["reactive", "web", "html", "browser", "dom"]

[dependencies]
silkenweb = "0.2.0"
web-sys = "0.3"
wasm-bindgen = "=0.2.78"
js-sys = "0.3"
parse-display= "0.5"
