[package]
name = "silkenweb-js-framework-benchmark"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O4']

[lib]
crate-type = ["cdylib"]

[dependencies]
silkenweb = "0.1"
futures-signals = "0.3"
js-sys = "0.3"
wasm-bindgen = {version = "=0.2.78", features = ["enable-interning"]}
rand = {version = "0.8", features = ["small_rng"]}
getrandom = { version = "0.2", features = ["js"] }
