[package]
name = "silkenweb-core"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.73"
num-traits = "0.2"

[dependencies.web-sys]
version = "0.3"
features = ["Window", "Document", "Text"]
