[package]
name = "silkenweb-tutorial-common"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
silkenweb = { path = "../../crates/silkenweb" }
