[package]
name = "silkenweb-example-hydration"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = { path = "../../packages/silkenweb", features = ["hydration"] }
futures-signals = "0.3.31"
web-log = "1.0.1"