[package]
name = "silkenweb-example-hydration"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = { path = "../../crates/silkenweb", features = ["hydration"] }
futures-signals = "0.3"
