[package]
name = "silkenweb-example-ssr"
version = "0.1.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
silkenweb = { path = "../../packages/silkenweb", features = ["server-side-render"] }
futures-signals = "0.3.31"
