name: tests
on: [push, pull_request]
jobs:
  non-web-tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [1.57]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        default: true
        components: clippy
    - uses: Swatinem/rust-cache@3bb3a9a087029c7bc392586cdc88cb6f66b9c6ef
      if: ${{ !env.ACT }}
    - run: cargo xtask ci stable

  browser-tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [1.57]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        default: true
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        target: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@3bb3a9a087029c7bc392586cdc88cb6f66b9c6ef
      if: ${{ !env.ACT }}
    - uses: actions-rs/install@v0.1
      with:
        crate: wasm-pack
        version: 0.10.2
    - uses: actions-rs/install@v0.1
      with:
        crate: trunk
        version: 0.14.0
    - uses: actions-rs/install@v0.1
      with:
        crate: wasm-bindgen-cli
        version: 0.2.78
    - name: Browser Tests
      run: cargo xtask ci browser
    # Screenshots are only generated on failure
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: todomvc-cypress-screenshots
        path: examples/todomvc/e2e/cypress/screenshots
    # Videos are generated regardless of success or failure
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: todomvc-cypress-videos
        path: examples/todomvc/e2e/cypress/videos

  nightly:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly-2021-12-19]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        default: true
        components: rustfmt
    - uses: Swatinem/rust-cache@3bb3a9a087029c7bc392586cdc88cb6f66b9c6ef
      if: ${{ !env.ACT }}
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-udeps
    - run: cargo xtask ci nightly ${{ matrix.rust }}
