name: Tests
on: [push, pull_request]
jobs:
  non-web-tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [1.51]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
    - run: rustup toolchain install ${{ matrix.rust }} -c clippy
    - run: rustup default ${{ matrix.rust }}
    - run: cargo clippy --all-targets -- -D warnings -D clippy::pedantic -D clippy::all
    - run: cargo build --all-targets
    - run: cargo test
    - run: cargo test --benches --tests --release

  browser-tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [1.51]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
    - run: rustup toolchain install ${{ matrix.rust }}
    - run: rustup default ${{ matrix.rust }}
    - run: cargo install wasm-bindgen-cli --version 0.2.73
    - run: cargo install wasm-pack
    - run: cargo install trunk
    - name: Browser Tests
      run: wasm-pack test --headless --firefox --chrome
      working-directory: crates/silkenweb
    - name: Cypress tests
      # Not sure why this doesn't work. Need to get access to a Mac to test.
      if: matrix.os != 'macos-latest'
      working-directory: examples/todomvc
      run: |
        bash install-cypress.sh
        bash run-cypress-tests.sh
    
  nightly:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly-2021-04-25]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
    - run: rustup toolchain install ${{ matrix.rust }} -c rustfmt
    - run: cargo install cargo-udeps
    - run: rustup default ${{ matrix.rust }}
    - run: cargo fmt --all -- --check
    - run: cargo udeps --all-targets

  book:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.51]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
    - run: cargo install mdbook
    - run: mdbook test
      working-directory: tutorial
