name: tests
on: [push, pull_request]
jobs:
  non-web-tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [1.55]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        default: true
        components: clippy
    - run: cargo clippy --all-targets -- -D warnings -D clippy::pedantic -D clippy::all
    - run: cargo build --all-targets
    - run: cargo test
    - run: cargo test --benches --tests --release

  browser-tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [1.55]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        default: true
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        target: wasm32-unknown-unknown
    - uses: actions-rs/install@v0.1
      with:
        crate: wasm-pack
        version: 0.9.1
    - uses: actions-rs/install@v0.1
      with:
        crate: trunk
        version: 0.10.0
    - uses: actions-rs/install@v0.1
      with:
        crate: wasm-bindgen-cli
        version: 0.2.73
    - name: Browser Tests
      # TODO: Chromium tests fail under `act`
      run: wasm-pack test --headless --firefox
      working-directory: crates/silkenweb
    - name: Cypress tests
      # TODO: Not sure why this doesn't work. Need to get access to a Mac to test.
      if: matrix.os != 'macos-latest'
      working-directory: examples/todomvc
      run: |
        bash install-cypress.sh
        bash run-cypress-tests.sh

  nightly:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly-2021-09-16]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        default: true
        components: rustfmt
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-udeps
    - run: cargo fmt --all -- --check
    - run: cargo udeps --all-targets

  book:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.55]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        default: true
    - uses: actions-rs/install@v0.1
      with:
        crate: mdbook
    - run: mdbook test
      working-directory: tutorial
