name: website
on: 
  push:
    branches:
      - main
jobs:
  deploy-website:
    env:
      rust: 1.73
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ env.rust }}
        default: true
        components: clippy
        target: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/install@v0.1
      with:
        crate: trunk
        version: 0.17.2
    - name: Build Website
      run: cargo xtask build-website
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: 'target/website'
        production-deploy: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
